require "gobject"
require "./lib_cairo"
require "./surface.cr"
require "./font_face.cr"
require "./font_options.cr"
require "./device.cr"
require "./matrix.cr"
require "./region.cr"
require "./context.cr"
require "./scaled_font.cr"
require "./path.cr"
require "./module_functions.cr"
require "./pattern.cr"
require "./status_exception.cr"

